### ISSUE TITLE
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by natea** [mistio/mist-ce#1014]
When I try to download and install Mist using the instructions at https://github.com/mistio/mist-ce/releases/tag/v4.5.5

I get the following error:

```
% docker-compose up -d
Pulling mongodb (mongo:3.2)...
3.2: Pulling from library/mongo
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by d-mo** [comment]
Hi @natea !

Looks like there's no mongodb:3.2 Docker image for arm64.

You can try editing docker-compose.yml and replacing the mongo:3.2 image with one of these https://hub.docker.com/r/arm64v8/mongo/tags

**Comment by natea** [comment]
Thanks! I changed this line in the docker-compose.yml file to this:

```
 mongodb:
    image: arm64v8/mongo
    restart: on-failure:5
    volumes:
      - mongodb:/data/db:rw
```

But I think it may not just be MongoDB, but other images as well?

```
⠿ nginx Error                                                                                                                                                   0.8s
 ⠿ mongodb Error                                                                                                                                                 0.8s
 ⠿ elasticsearch-manage Error                                                                                                                                    0.8s
 ⠿ elasticsearch Error                                                                                                                                           0.8s
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by natea** [comment]
btw, I'm trying to run Mist on my new Macbook M1 (non-Intel). Do you think that's foolhardy, and I should just run the docker-compose on a Intel-based VM in the cloud?

Nate

**Comment by d-mo** [comment]
I'm not aware of any similar attempts just yet, so I'm not sure if it can be done easily. Better stick with x86_64 for now, unless you're feeling adventurous!

BTW 
1. Mist CE v4.6.0 will be released by the end of this week. It includes quite a few improvements and fixes.
2. Check out https://github.com/mistio/mist-cli

**Comment by natea** [comment]
Is it possible to talk directly to the Mist API, or only via the CLI tool?

I'm looking at your documentation on this page: https://docs.mist.io/article/78-launching-vms

And the links to these pages all give 404s:

https://docs.mist.io/article/37-authenticating-with-the-mist-io-api

https://docs.mist.io/article/60-quickstart

https://docs.mist.io/article/38-introduction

Website: http://www.appsembler.com ( http://www.appsembler.com/ )
Blog: http://www.appsembler.com/blog
Twitter: http://twitter.com/natea
LinkedIn: http://linkedin.com/in/natea

Phone: +1 (617) 702-4331

**Comment by d-mo** [comment]
Sure. The docs for API v1 are available at https://mist.io/swagger/

There's also API v2 https://mist.io/api/v2
It's better structured with more features but could change a bit until Mist v5.0.0 early next year. The CLI works with API v2.

Thanks for the heads up regarding the dead links.

**Comment by d-mo** [comment]
Hi @natea.

I got my hands on a new Macbook Air and I was able to make Mist CE work on it. 

If you want to try it out check the m1 branch. You'll need the [dev deployment](https://github.com/mistio/mist-ce/tree/m1#development-deployment):
```
git checkout m1
git submodule update
docker-compose up -d
```
I had to upgrade Elasticsearch to make it work. I have not tested it extensively yet.

**Comment by natea** [comment]
Thanks @d-mo ! I followed your instructions, but ran into some errors:

```
Status: Downloaded newer image for mistce/elasticsearch-manage:m1
Creating mist-ce_ui_1            ... done
Creating mist-ce_influxdb_1      ... done
Creating mist-ce_elasticsearch_1 ... done
Creating mist-ce_swagger_1       ... done
Creating mist-ce_traefik_1       ... done
Creating mist-ce_landing_1       ... done
Creating mist-ce_mailmock_1      ... done
Creating mist-ce_socat_1         ... done
Creating mist-ce_wsproxy_1       ... done
Creating mist-ce_vminsert_1      ... done
Creating mist-ce_kibana_1               ... done
Creating mist-ce_huproxy_1       ... done
Creating mist-ce_rabbitmq_1      ... done
Creating mist-ce_vmstorage_1     ... done
Creating mist-ce_debugger_1      ... done
Creating mist-ce_memcached_1     ... done
Creating mist-ce_gocky_1                ... done
Creating mist-ce_gocky_1         ...
Creating mist-ce_sockjs_1        ...
Creating mist-ce_api_1           ...
Creating mist-ce_api-v2_1        ...
Creating mist-ce_elasticsearch-manage_1 ...
Creating mist-ce_dramatiq_1             ...
Creating mist-ce_api_1                  ... error
Creating mist-ce_logstash_1             ...
Creating mist-ce_scheduler_1            ... error
Creating mist-ce_sockjs_1               ... error
ERROR: for mist-ce_scheduler_1  Cannot start service scheduler: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mi
Creating mist-ce_logstash_1             ... done
ry: unknown
Creating mist-ce_kibana_1               ... done
ERROR: for mist-ce_api_1  Cannot start service api: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for mist-ce_sockjs_1  Cannot start service sockjs: OCI runtime create fai
Creating mist-ce_apply-migrations_1     ... error
Creating mist-ce_api-v2_1               ... error
known

ERROR: for mist-ce_apply-migrations_1  Cannot start service apply-migrations: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown
Creating mist-ce_dramatiq_1             ... error
ERROR: for mist-ce_api-v2_1  Cannot start service api-v2: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: un
Creating mist-ce_elasticsearch-manage_1 ... done

ERROR: for mist-ce_dramatiq_1  Cannot start service dramatiq: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for scheduler  Cannot start service scheduler: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for api  Cannot start service api: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for sockjs  Cannot start service sockjs: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for apply-migrations  Cannot start service apply-migrations: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for api-v2  Cannot start service api-v2: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for dramatiq  Cannot start service dramatiq: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by d-mo** [comment]
Looks like you didn't checkout the submodules with `git clone --recursive ...`.

You can do that now with `git submodule update --init --recursive`. Then bring everything down and backup up.

**Comment by natea** [comment]
Do I need to wipe the entire github repo, and start over?

```
nateaune@MacBook-Pro mist-ce % git submodule update --init --recursive
Submodule 'api' (https://github.com/mistio/mist.api.git) registered for path 'api'
Submodule 'docker/nginx/static/novnc' (https://github.com/novnc/noVNC.git) registered for path 'docker/nginx/static/novnc'
Submodule 'landing' (https://github.com/mistio/mist.landing.git) registered for path 'landing'
Submodule 'tests' (https://github.com/mistio/mist.tests.git) registered for path 'tests'
Submodule 'ui' (https://github.com/mistio/mist.ui.git) registered for path 'ui'
Cloning into '/Users/nateaune/Documents/code/mist-ce/api'...
fatal: destination path '/Users/nateaune/Documents/code/mist-ce/landing' already exists and is not an empty directory.
fatal: clone of 'https://github.com/mistio/mist.landing.git' into submodule path '/Users/nateaune/Documents/code/mist-ce/landing' failed
Failed to clone 'landing'. Retry scheduled
fatal: destination path '/Users/nateaune/Documents/code/mist-ce/landing' already exists and is not an empty directory.
fatal: clone of 'https://github.com/mistio/mist.landing.git' into submodule path '/Users/nateaune/Documents/code/mist-ce/landing' failed
Failed to clone 'landing' a second time, aborting
Cloning into '/Users/nateaune/Documents/code/mist-ce/docker/nginx/static/novnc'...
Cloning into '/Users/nateaune/Documents/code/mist-ce/tests'...
Cloning into '/Users/nateaune/Documents/code/mist-ce/ui'...
nateaune@MacBook-Pro mist-ce % docker-compose down
Stopping mist-ce_logstash_1  ... done
Stopping mist-ce_gocky_1     ... done
Stopping mist-ce_memcached_1 ... done
Stopping mist-ce_debugger_1  ... done
Stopping mist-ce_mongodb_1   ... done
Stopping mist-ce_huproxy_1   ... done
Stopping mist-ce_vminsert_1  ... done
Stopping mist-ce_vmstorage_1 ... done
Stopping mist-ce_rabbitmq_1  ... done
Stopping mist-ce_mailmock_1  ... done
Stopping mist-ce_landing_1   ... done
Stopping mist-ce_vmselect_1  ... done
Stopping mist-ce_wsproxy_1   ... done
Stopping mist-ce_socat_1     ... done
Stopping mist-ce_traefik_1   ... done
Stopping mist-ce_swagger_1   ... done
Stopping mist-ce_influxdb_1  ... done
Stopping mist-ce_ui_1        ... done
Removing mist-ce_apply-migrations_1     ...
Removing mist-ce_kibana_1               ...
Removing mist-ce_api_1                  ...
Removing mist-ce_api_1                  ... done
Removing mist-ce_elasticsearch-manage_1 ... done
Removing mist-ce_logstash_1             ... done
Removing mist-ce_dramatiq_1             ... done
Removing mist-ce_api-v2_1               ... done
Removing mist-ce_sockjs_1               ... done
Removing mist-ce_gocky_1                ... done
Removing mist-ce_memcached_1            ... done
Removing mist-ce_debugger_1             ... done
Removing mist-ce_mongodb_1              ... done
Removing mist-ce_huproxy_1              ... done
Removing mist-ce_vminsert_1             ... done
Removing mist-ce_vmstorage_1            ... done
Removing mist-ce_rabbitmq_1             ... done
Removing mist-ce_mailmock_1             ... done
Removing mist-ce_landing_1              ... done
Removing mist-ce_vmselect_1             ... done
Removing mist-ce_wsproxy_1              ... done
Removing mist-ce_socat_1                ... done
Removing mist-ce_traefik_1              ... done
Removing mist-ce_swagger_1              ... done
Removing mist-ce_elasticsearch_1        ... done
Removing mist-ce_influxdb_1             ... done
Removing mist-ce_ui_1                   ... done
Removing network mist-ce_default
nateaune@MacBook-Pro mist-ce % docker-compose up -d
Creating network "mist-ce_default" with the default driver
Creating mist-ce_influxdb_1      ... done
Creating mist-ce_traefik_1       ... done
Creating mist-ce_memcached_1     ... done
Creating mist-ce_swagger_1       ... done
Creating mist-ce_socat_1         ... done
Creating mist-ce_elasticsearch_1 ... done
Creating mist-ce_huproxy_1       ... done
Creating mist-ce_mongodb_1       ... done
Creating mist-ce_landing_1              ... done
Creating mist-ce_vmselect_1             ... done
Creating mist-ce_ui_1            ... done
Creating mist-ce_vmstorage_1            ... done
Creating mist-ce_debugger_1             ... done
Creating mist-ce_wsproxy_1       ... done
Creating mist-ce_vminsert_1      ... done
Creating mist-ce_mailmock_1             ... done
Creating mist-ce_rabbitmq_1      ... done
Creating mist-ce_kibana_1               ... done
Creating mist-ce_scheduler_1     ...
Creating mist-ce_gocky_1         ...
Creating mist-ce_elasticsearch-manage_1 ...
Creating mist-ce_api-v2_1               ...
Creating mist-ce_elasticsearch-manage_1 ... done
Creating mist-ce_apply-migrations_1     ...
Creating mist-ce_dramatiq_1             ...
Creating mist-ce_gocky_1                ... done
Creating mist-ce_dramatiq_1             ... error
Creating mist-ce_logstash_1             ... done
Creating mist-ce_scheduler_1            ... error
Creating mist-ce_api-v2_1               ... error
Creating mist-ce_sockjs_1               ... error

ERROR: for mist-ce_sockjs_1  Cannot start service sockjs: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for mist-ce_apply-migrations_1  Cannot start service apply-migrations: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for mist-ce_api-v2_1  Cannot start service api-v2: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for mist-ce_scheduler_1  Cannot start service scheduler: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for api  Cannot start service api: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for dramatiq  Cannot start service dramatiq: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for sockjs  Cannot start service sockjs: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for apply-migrations  Cannot start service apply-migrations: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for api-v2  Cannot start service api-v2: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown

ERROR: for scheduler  Cannot start service scheduler: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/mist.api/bin/docker-init": stat /mist.api/bin/docker-init: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by natea** [comment]
After wiping the github repo from my local machine, and cloning it again with `--recursive`, I was able to get all but the Kibana container running:

```
nateaune@MacBook-Pro mist-ce % docker-compose ps
NAME                             COMMAND                  SERVICE                STATUS              PORTS
mist-ce_api-v2_1                 "/mist.api/bin/docke…"   api-v2                 running             8080/tcp
mist-ce_api_1                    "/mist.api/bin/docke…"   api                    running             80/tcp
mist-ce_apply-migrations_1       "/mist.api/bin/docke…"   apply-migrations       running
mist-ce_debugger_1               "/entry.sh"              debugger               running             22/tcp
mist-ce_dramatiq_1               "/mist.api/bin/docke…"   dramatiq               running
mist-ce_elasticsearch-manage_1   "./scripts/add_templ…"   elasticsearch-manage   running
mist-ce_elasticsearch_1          "/bin/tini -- /usr/l…"   elasticsearch          running             0.0.0.0:9200->9200/tcp
mist-ce_gocky_1                  "/go/src/github.com/…"   gocky                  running             0.0.0.0:9096-9097->9096-9097/tcp
mist-ce_huproxy_1                "/app --listen 0.0.0…"   huproxy                running             8086/tcp
mist-ce_influxdb_1               "/entrypoint.sh infl…"   influxdb               running             0.0.0.0:8083->8083/tcp, 0.0.0.0:8086->8086/tcp
mist-ce_kibana_1                 "/docker-entrypoint.…"   kibana                 exited (2)
mist-ce_landing_1                "/entry.sh sh /entry…"   landing                running             8000/tcp
mist-ce_logstash_1               "/usr/local/bin/dock…"   logstash               running             9600/tcp
mist-ce_mailmock_1               "twistd -n localmail…"   mailmock               running             8025/tcp
mist-ce_memcached_1              "docker-entrypoint.s…"   memcached              running             11211/tcp
mist-ce_mongodb_1                "docker-entrypoint.s…"   mongodb                running             27017/tcp
mist-ce_nginx_1                  "nginx -g 'daemon of…"   nginx                  running             0.0.0.0:80->80/tcp
mist-ce_rabbitmq_1               "docker-entrypoint.s…"   rabbitmq               running             0.0.0.0:15672->15672/tcp
mist-ce_scheduler_1              "/mist.api/bin/docke…"   scheduler              running
mist-ce_socat_1                  "socat TCP4-LISTEN:2…"   socat                  running             2375/tcp
mist-ce_sockjs_1                 "/mist.api/bin/docke…"   sockjs                 running             8081/tcp
mist-ce_swagger_1                "sh /usr/share/nginx…"   swagger                running             8080/tcp
mist-ce_traefik_1                "/traefik --accesslo…"   traefik                running             0.0.0.0:8040->80/tcp, 0.0.0.0:8041->8080/tcp
mist-ce_ui_1                     "/entry.sh sh /entry…"   ui                     running             8000/tcp
mist-ce_vminsert_1               "/vminsert-prod --in…"   vminsert               running             0.0.0.0:63167->8480/tcp
mist-ce_vmselect_1               "/vmselect-prod --se…"   vmselect               running             0.0.0.0:63171->8481/tcp
mist-ce_vmstorage_1              "/vmstorage-prod --r…"   vmstorage              running             0.0.0.0:63168-63169->8400-8401/tcp, 0.0.0.0:63170->8482/tcp
mist-ce_wsproxy_1                "python3 wsproxy.py"     wsproxy                running             8764/tcp
```

But now when I go to `http://localhost` I get this error:

```
502 Bad Gateway
nginx/1.17.1
```

**Comment by natea** [comment]
Here's what I'm seeing in the Kibana logs in Docker Desktop:

```


Upgrade




natea

mist-ce_kibana_1
kibana:5.6.10
EXITED (2)





runtime: failed to create new OS thread (have 2 already; errno=22)

fatal error: newosproc


runtime stack:

runtime.throw(0x4cb21f, 0x9)

/usr/local/go/src/runtime/panic.go:566 +0x95

runtime.newosproc(0xc420028000, 0xc420037fc0)

/usr/local/go/src/runtime/os_linux.go:160 +0x194

runtime.newm(0x4d6db8, 0x0)

/usr/local/go/src/runtime/proc.go:1572 +0x132

runtime.main.func1()

/usr/local/go/src/runtime/proc.go:126 +0x36

runtime.systemstack(0x53ae00)

/usr/local/go/src/runtime/asm_amd64.s:298 +0x79

runtime.mstart()

/usr/local/go/src/runtime/proc.go:1079


goroutine 1 [running]:

runtime.systemstack_switch()

/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760

runtime.main()

/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768

runtime.goexit()

/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0

runtime: failed to create new OS thread (have 2 already; errno=22)

fatal error: newosproc


runtime stack:

runtime.throw(0x4cb21f, 0x9)

/usr/local/go/src/runtime/panic.go:566 +0x95

runtime.newosproc(0xc420028000, 0xc420037fc0)

/usr/local/go/src/runtime/os_linux.go:160 +0x194

runtime.newm(0x4d6db8, 0x0)

/usr/local/go/src/runtime/proc.go:1572 +0x132

runtime.main.func1()

/usr/local/go/src/runtime/proc.go:126 +0x36

runtime.systemstack(0x53ae00)

/usr/local/go/src/runtime/asm_amd64.s:298 +0x79

runtime.mstart()

/usr/local/go/src/runtime/proc.go:1079


goroutine 1 [running]:

runtime.systemstack_switch()

/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760

runtime.main()

/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768

runtime.goexit()

/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0

runtime: failed to create new OS thread (have 2 already; errno=22)

fatal error: newosproc


runtime stack:

runtime.throw(0x4cb21f, 0x9)

/usr/local/go/src/runtime/panic.go:566 +0x95

runtime.newosproc(0xc420028000, 0xc420037fc0)

/usr/local/go/src/runtime/os_linux.go:160 +0x194

runtime.newm(0x4d6db8, 0x0)

/usr/local/go/src/runtime/proc.go:1572 +0x132

runtime.main.func1()

/usr/local/go/src/runtime/proc.go:126 +0x36

runtime.systemstack(0x53ae00)

/usr/local/go/src/runtime/asm_amd64.s:298 +0x79

runtime.mstart()

/usr/local/go/src/runtime/proc.go:1079


goroutine 1 [running]:

runtime.systemstack_switch()

/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760

runtime.main()

/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768

runtime.goexit()

/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0

runtime: failed to create new OS thread (have 2 already; errno=22)

fatal error: newosproc


runtime stack:

runtime.throw(0x4cb21f, 0x9)

/usr/local/go/src/runtime/panic.go:566 +0x95

runtime.newosproc(0xc420028000, 0xc420037fc0)

/usr/local/go/src/runtime/os_linux.go:160 +0x194

runtime.newm(0x4d6db8, 0x0)

/usr/local/go/src/runtime/proc.go:1572 +0x132

runtime.main.func1()

/usr/local/go/src/runtime/proc.go:126 +0x36

runtime.systemstack(0x53ae00)

/usr/local/go/src/runtime/asm_amd64.s:298 +0x79

runtime.mstart()

/usr/local/go/src/runtime/proc.go:1079


goroutine 1 [running]:

runtime.systemstack_switch()

/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760

runtime.main()

/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768

runtime.goexit()

/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0

runtime: failed to create new OS thread (have 2 already; errno=22)

fatal error: newosproc


runtime stack:

runtime.throw(0x4cb21f, 0x9)

/usr/local/go/src/runtime/panic.go:566 +0x95

runtime.newosproc(0xc420028000, 0xc420037fc0)

/usr/local/go/src/runtime/os_linux.go:160 +0x194

runtime.newm(0x4d6db8, 0x0)

/usr/local/go/src/runtime/proc.go:1572 +0x132

runtime.main.func1()

/usr/local/go/src/runtime/proc.go:126 +0x36

runtime.systemstack(0x53ae00)

/usr/local/go/src/runtime/asm_amd64.s:298 +0x79

runtime.mstart()

/usr/local/go/src/runtime/proc.go:1079


goroutine 1 [running]:

runtime.systemstack_switch()

/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760

runtime.main()

/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768

runtime.goexit()

/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0

runtime: failed to create new OS thread (have 2 already; errno=22)

fatal error: newosproc


runtime stack:

runtime.throw(0x4cb21f, 0x9)

/usr/local/go/src/runtime/panic.go:566 +0x95

runtime.newosproc(0xc420028000, 0xc420037fc0)

/usr/local/go/src/runtime/os_linux.go:160 +0x194

runtime.newm(0x4d6db8, 0x0)

/usr/local/go/src/runtime/proc.go:1572 +0x132

runtime.main.func1()

/usr/local/go/src/runtime/proc.go:126 +0x36

runtime.systemstack(0x53ae00)

/usr/local/go/src/runtime/asm_amd64.s:298 +0x79

runtime.mstart()

/usr/local/go/src/runtime/proc.go:1079


goroutine 1 [running]:

runtime.systemstack_switch()

/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760

runtime.main()

/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768

runtime.goexit()

/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0

runtime: failed to create new OS thread (have 2 already; errno=22)

fatal error: newosproc


runtime stack:

runtime.throw(0x4cb21f, 0x9)

/usr/local/go/src/runtime/panic.go:566 +0x95

runtime.newosproc(0xc420028000, 0xc420037fc0)

/usr/local/go/src/runtime/os_linux.go:160 +0x194

runtime.newm(0x4d6db8, 0x0)

/usr/local/go/src/runtime/proc.go:1572 +0x132

runtime.main.func1()

/usr/local/go/src/runtime/proc.go:126 +0x36

runtime.systemstack(0x53ae00)

/usr/local/go/src/runtime/asm_amd64.s:298 +0x79

runtime.mstart()

/usr/local/go/src/runtime/proc.go:1079


goroutine 1 [running]:

runtime.systemstack_switch()

/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760

runtime.main()

/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768

runtime.goexit()

/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0

runtime: failed to create new OS thread (have 2 already; errno=22)

fatal error: newosproc


runtime stack:

runtime.throw(0x4cb21f, 0x9)

/usr/local/go/src/runtime/panic.go:566 +0x95

runtime.newosproc(0xc420028000, 0xc420037fc0)

/usr/local/go/src/runtime/os_linux.go:160 +0x194

runtime.newm(0x4d6db8, 0x0)

/usr/local/go/src/runtime/proc.go:1572 +0x132

runtime.main.func1()

/usr/local/go/src/runtime/proc.go:126 +0x36

runtime.systemstack(0x53ae00)

/usr/local/go/src/runtime/asm_amd64.s:298 +0x79

runtime.mstart()

/usr/local/go/src/runtime/proc.go:1079


goroutine 1 [running]:

runtime.systemstack_switch()

/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760

runtime.main()

/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768

runtime.goexit()

/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0

runtime: failed to create new OS thread (have 2 already; errno=22)

fatal error: newosproc


runtime stack:

runtime.throw(0x4cb21f, 0x9)

/usr/local/go/src/runtime/panic.go:566 +0x95

runtime.newosproc(0xc420028000, 0xc420037fc0)

/usr/local/go/src/runtime/os_linux.go:160 +0x194

runtime.newm(0x4d6db8, 0x0)

/usr/local/go/src/runtime/proc.go:1572 +0x132

runtime.main.func1()

/usr/local/go/src/runtime/proc.go:126 +0x36

runtime.systemstack(0x53ae00)

/usr/local/go/src/runtime/asm_amd64.s:298 +0x79

runtime.mstart()

/usr/local/go/src/runtime/proc.go:1079


goroutine 1 [running]:

runtime.systemstack_switch()

/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760

runtime.main()

/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768

runtime.goexit()

/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0

runtime: failed to create new OS thread (have 2 already; errno=22)

fatal error: newosproc


runtime stack:

runtime.throw(0x4cb21f, 0x9)

/usr/local/go/src/runtime/panic.go:566 +0x95

runtime.newosproc(0xc420028000, 0xc420037fc0)

/usr/local/go/src/runtime/os_linux.go:160 +0x194

runtime.newm(0x4d6db8, 0x0)

/usr/local/go/src/runtime/proc.go:1572 +0x132

runtime.main.func1()

/usr/local/go/src/runtime/proc.go:126 +0x36

runtime.systemstack(0x53ae00)

/usr/local/go/src/runtime/asm_amd64.s:298 +0x79

runtime.mstart()

/usr/local/go/src/runtime/proc.go:1079


goroutine 1 [running]:

runtime.systemstack_switch()

/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760

runtime.main()

/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768

runtime.goexit()

/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0

runtime: failed to create new OS thread (have 2 already; errno=22)

fatal error: newosproc


runtime stack:

runtime.throw(0x4cb21f, 0x9)

/usr/local/go/src/runtime/panic.go:566 +0x95

runtime.newosproc(0xc420028000, 0xc420037fc0)

/usr/local/go/src/runtime/os_linux.go:160 +0x194

runtime.newm(0x4d6db8, 0x0)

/usr/local/go/src/runtime/proc.go:1572 +0x132

runtime.main.func1()

/usr/local/go/src/runtime/proc.go:126 +0x36

runtime.systemstack(0x53ae00)

/usr/local/go/src/runtime/asm_amd64.s:298 +0x79

runtime.mstart()

/usr/local/go/src/runtime/proc.go:1079


goroutine 1 [running]:

runtime.systemstack_switch()

/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760

runtime.main()

/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768

runtime.goexit()

/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0

runtime: failed to create new OS thread (have 2 already; errno=22)

fatal error: newosproc


runtime stack:

runtime.throw(0x4cb21f, 0x9)

/usr/local/go/src/runtime/panic.go:566 +0x95

runtime.newosproc(0xc420028000, 0xc420037fc0)

/usr/local/go/src/runtime/os_linux.go:160 +0x194

runtime.newm(0x4d6db8, 0x0)

/usr/local/go/src/runtime/proc.go:1572 +0x132

runtime.main.func1()

/usr/local/go/src/runtime/proc.go:126 +0x36

runtime.systemstack(0x53ae00)

/usr/local/go/src/runtime/asm_amd64.s:298 +0x79

runtime.mstart()

/usr/local/go/src/runtime/proc.go:1079


goroutine 1 [running]:

runtime.systemstack_switch()

/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420022768 sp=0xc420022760

runtime.main()

/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227c0 sp=0xc420022768

runtime.goexit()

/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200227c8 sp=0xc4200227c0
```

**Comment by d-mo** [comment]
Yes, I didn't get Kibana to work, but it's not really necessary. It's mostly there for debugging.
