### ISSUE TITLE
Error when addind KVM node

### ISSUE THREAD

**Issue by chewdevs** [mistio/mist-ce#949]
I'm using 3.3.1. 
The KVM node is using Ubuntu 18.04. 

When I try to add a KVM host, I get the following error:
```
api_1                   | 2018-12-27 15:22:52,332 INFO  [mist.api.clouds.methods][uWSGIWorker1Core0] Adding new cloud in provider 'libvirt'
api_1                   | 2018-12-27 15:22:52,336 WARNI [mist.api.helpers][uWSGIWorker1Core0] Got param 'machine_hostname' when expecting 'host', transforming.
api_1                   | 2018-12-27 15:22:52,336 WARNI [mist.api.helpers][uWSGIWorker1Core0] Got param 'machine_user' when expecting 'username', transforming.
api_1                   | 2018-12-27 15:22:52,336 WARNI [mist.api.helpers][uWSGIWorker1Core0] Got param 'machine_key' when expecting 'key', transforming.
api_1                   | 2018-12-27 15:22:52,336 WARNI [mist.api.helpers][uWSGIWorker1Core0] Got param 'ssh_port' when expecting 'port', transforming.
api_1                   | 2018-12-27 15:22:53,527 INFO  [paramiko.transport][Thread-3] Connected (version 2.0, client OpenSSH_7.6p1)
api_1                   | 2018-12-27 15:22:53,647 INFO  [paramiko.transport][Thread-3] Authentication (publickey) successful!
api_1                   | 2018-12-27 15:22:53,886 ERROR [mist.api.clouds.controllers.compute.base][uWSGIWorker1Core0] Error while running list_nodes on <class 'mist.api.clouds.models.LibvirtCloud'> cloud KVM (libvirt) (aef66c27ac85418cbc175643bfa419ee) of Org laurent2.perrin@orange.com (1 teams - 1 members)
api_1                   | Traceback (most recent call last):
api_1                   |   File "/mist.api/src/mist/api/clouds/controllers/compute/base.py", line 268, in _list_machines
api_1                   |     nodes = self._list_machines__fetch_machines()
api_1                   |   File "/mist.api/src/mist/api/clouds/controllers/compute/base.py", line 539, in _list_machines__fetch_machines
api_1                   |     return self.connection.list_nodes()
api_1                   |   File "/mist.api/libcloud/libcloud/compute/drivers/libvirt_driver.py", line 192, in list_nodes
api_1                   |     self.arp_table = self._parse_arp_table(self._run_command(cmd).get('output'))
api_1                   |   File "/mist.api/libcloud/libcloud/compute/drivers/libvirt_driver.py", line 1071, in _run_command
api_1                   |     return {'output': output.decode(), 'error': error.decode()}
api_1                   | UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
api_1                   | 2018-12-27 15:22:53,895 ERROR [mist.api.clouds.controllers.main.base][uWSGIWorker1Core0] Will not update cloud <class 'mist.api.clouds.models.LibvirtCloud'> cloud KVM (libvirt) (aef66c27ac85418cbc175643bfa419ee) of Org laurent2.perrin@orange.com (1 teams - 1 members) because we couldn't connect: CloudUnavailableError('Cloud unavailable',)
api_1                   | 2018-12-27 15:22:53,900 INFO  [mist.api.views][uWSGIWorker1Core0] MistError: CloudUnavailableError('Cloud unavailable',)
api_1                   | [pid: 63|app: 0|req: 2/9] 172.18.0.27 () {44 vars in 837 bytes} [Thu Dec 27 15:22:52 2018] POST /api/v1/clouds => generated 17 bytes in 1601 msecs (HTTP/1.0 503) 2 headers in 96 bytes (1 switches on core 0)
```

**Comment by d-mo** [comment]
Thanks for the heads up. This should go away in the upcoming 4.0.0 release which will be using Python 3.7.

In the meantime, you should be able to patch your local installation manually:
1. Open the libvirt_driver.py file within the api container with vi: `docker-compose exec api vi /mist.api/libcloud/libcloud/compute/drivers/libvirt_driver.py`
2. Change `output.decode()` and `error.decode()` in line 1071 to `output.decode('utf-8', 'ignore')` and `error.decode('utf-8', 'ignore')` respectively
3. Save file and exit the editor
4. Restart the api container `docker-compose restart api`

**Comment by chewdevs** [comment]
Thanks for the workaround, now the KVM node can be added !
