### ISSUE TITLE
docker-compose up faild

### ISSUE THREAD

**Issue by ghoul008** [mistio/mist-ce#970]
Hi i used 4.2.0 and 4.2.1 get seem err,my docker version 19.03.5 (centos7)
`[sanshan@localhost ~]$ docker-compose ps
             Name                           Command               State                   Ports                
---------------------------------------------------------------------------------------------------------------
sanshan_api_1                    /mist.api/bin/docker-init  ...   Up       80/tcp                              
sanshan_apply-migrations_1       /mist.api/bin/docker-init  ...   Exit 1                                       
sanshan_beat_1                   /mist.api/bin/docker-init  ...   Up                                           
sanshan_celery-gevent_1          /mist.api/bin/docker-init  ...   Up                                           
sanshan_celery-prefork_1         /mist.api/bin/docker-init  ...   Up                                           
sanshan_cilia_1                  /mist.api/bin/docker-init  ...   Up                                           
sanshan_elasticsearch-manage_1   ./scripts/add_templates.py       Exit 1                                       
sanshan_elasticsearch_1          /docker-entrypoint.sh elas ...   Up       9200/tcp, 9300/tcp                  
sanshan_gocky_1                  /go/src/github.com/mistio/ ...   Up       0.0.0.0:9096->9096/tcp,             
                                                                           0.0.0.0:9097->9097/tcp              
sanshan_hubshell_1               /mist.api/bin/docker-init  ...   Up                                           
sanshan_influxdb_1               /entrypoint.sh influxd           Up       0.0.0.0:8083->8083/tcp,             
                                                                           0.0.0.0:8086->8086/tcp              
sanshan_kibana_1                 /docker-entrypoint.sh kibana     Up       5601/tcp                            
sanshan_landing_1                sh /entry.sh                     Up       80/tcp                              
sanshan_logstash_1               /docker-entrypoint.sh logs ...   Up                                           
sanshan_mailmock_1               twistd -n localmail --smtp ...   Up       8025/tcp                            
sanshan_memcached_1              docker-entrypoint.sh memcached   Up       11211/tcp                           
sanshan_mongodb_1                docker-entrypoint.sh mongod      Up       27017/tcp                           
sanshan_nginx_1                  nginx -g daemon off;             Up       0.0.0.0:80->80/tcp                  
sanshan_poller_1                 /mist.api/bin/docker-init  ...   Up                                           
sanshan_rabbitmq_1               docker-entrypoint.sh rabbi ...   Up       15671/tcp, 15672/tcp, 25672/tcp,    
                                                                           4369/tcp, 5671/tcp, 5672/tcp        
sanshan_scheduler_1              /mist.api/bin/docker-init  ...   Up                                           
sanshan_socat_1                  socat TCP4-LISTEN:2375,for ...   Up       2375/tcp                            
sanshan_sockjs_1                 /mist.api/bin/docker-init  ...   Up       8081/tcp                            
sanshan_swagger_1                sh /usr/share/nginx/docker ...   Up       8080/tcp                            
sanshan_traefik_1                /traefik --accesslog --api ...   Up       0.0.0.0:8040->80/tcp,               
                                                                           0.0.0.0:8041->8080/tcp              
sanshan_ui_1                     sh /entry.sh                     Up       80/tcp   `

sanshan_apply-migrations_1 logs
`Waiting for elasticsearch:9200
UP: elasticsearch:9200
Waiting for mongodb:27017
UP: mongodb:27017
Waiting for rabbitmq:5672
UP: rabbitmq:5672
Waiting for memcached:11211
UP: memcached:11211
Will execute command bin/migrate
MIST_API_DIR is /mist.api
Couldn't find core config in /src/mist/core/config.py
Reading settings from /etc/mist/defaults.py
Reading settings from /etc/mist/settings/settings.py
2020-01-13 01:08:09 INFO MainThread __init__ - mongo_connect: Attempting to connect to mist2 at mongodb:27017...
2020-01-13 01:08:09 INFO MainThread __init__ - mongo_connect: Connected...
2020-01-13 01:08:09 INFO MainThread models - apply_migrations: Applying 0004-migrate-machine-logs.py
MIST_API_DIR is /mist.api
Couldn't find core config in /src/mist/core/config.py
Reading settings from /etc/mist/defaults.py
Reading settings from /etc/mist/settings/settings.py
2020-01-13 01:08:10 INFO MainThread __init__ - mongo_connect: Attempting to connect to mist2 at mongodb:27017...
2020-01-13 01:08:10 INFO MainThread __init__ - mongo_connect: Connected...
Connected to: elasticsearch
Traceback (most recent call last):
  File "/mist.api/migrations/0004-migrate-machine-logs.py", line 137, in <module>
    print_missing=args.print_missing
  File "/mist.api/migrations/0004-migrate-machine-logs.py", line 54, in migrate_machine_logs
    size=batch_size
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 660, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index')
Traceback (most recent call last):
  File "bin/migrate", line 68, in <module>
    main()
  File "bin/migrate", line 28, in main
    portal.apply_migrations()
  File "/mist.api/src/mist/api/portal/models.py", line 109, in apply_migrations
    '%s' % (proc.returncode, mig_num))
Exception: Error 1 while applying migration 4
Waiting for elasticsearch:9200
UP: elasticsearch:9200
Waiting for mongodb:27017
UP: mongodb:27017
Waiting for rabbitmq:5672
UP: rabbitmq:5672
Waiting for memcached:11211
UP: memcached:11211
Will execute command bin/migrate
MIST_API_DIR is /mist.api
Couldn't find core config in /src/mist/core/config.py
Reading settings from /etc/mist/defaults.py
Reading settings from /etc/mist/settings/settings.py
2020-01-13 01:08:15 INFO MainThread __init__ - mongo_connect: Attempting to connect to mist2 at mongodb:27017...
2020-01-13 01:08:15 INFO MainThread __init__ - mongo_connect: Connected...
2020-01-13 01:08:15 INFO MainThread models - apply_migrations: Applying 0004-migrate-machine-logs.py
MIST_API_DIR is /mist.api
Couldn't find core config in /src/mist/core/config.py
Reading settings from /etc/mist/defaults.py
Reading settings from /etc/mist/settings/settings.py
2020-01-13 01:08:15 INFO MainThread __init__ - mongo_connect: Attempting to connect to mist2 at mongodb:27017...
2020-01-13 01:08:15 INFO MainThread __init__ - mongo_connect: Connected...
Connected to: elasticsearch
Traceback (most recent call last):
  File "/mist.api/migrations/0004-migrate-machine-logs.py", line 137, in <module>
    print_missing=args.print_missing
  File "/mist.api/migrations/0004-migrate-machine-logs.py", line 54, in migrate_machine_logs
    size=batch_size
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 660, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index')
Traceback (most recent call last):
  File "bin/migrate", line 68, in <module>
    main()
  File "bin/migrate", line 28, in main
    portal.apply_migrations()
  File "/mist.api/src/mist/api/portal/models.py", line 109, in apply_migrations
    '%s' % (proc.returncode, mig_num))
Exception: Error 1 while applying migration 4
`

sanshan_elasticsearch-manage_1 logs
`Elasticsearch not up yet
Elasticsearch not up yet
Elasticsearch not up yet
Connected to: elasticsearch
Applying "cloudify-metrics" template... OK
Applying "machines_inventory" template... OK
Applying "exceptions" template... OK
Applying "logs" template... ERROR
Traceback (most recent call last):
  File "./scripts/add_templates.py", line 68, in add_templates
    es.indices.put_template(name=tname, body=template)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/indices.py", line 564, in put_template
    "PUT", _make_path("_template", name), params=params, body=body
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Field [_id] is defined twice in [request]')
Traceback (most recent call last):
  File "./scripts/add_templates.py", line 91, in <module>
    add_templates(args.force)
  File "./scripts/add_templates.py", line 76, in add_templates
    raise Exception("Completed with errors")
Exception: Completed with errors
Connected to: elasticsearch
Applying "cloudify-metrics" template... OK
Applying "machines_inventory" template... OK
Applying "exceptions" template... OK
Applying "logs" template... ERROR
`
why es is not work，THX。
i can sign in,but nothing.

**Comment by d-mo** [comment]
Most likely there is not enough RAM available for Elasticsearch. Check the elasticsearch container logs to confirm with `docker-compose logs elasticsearch`.

If you can't provide more RAM, then a patch like the following might somewhat reduce the memory requirements for elasticsearch.

```diff --git a/docker-compose.yml b/docker-compose.yml
index 42eccf376..d039ef92e 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -26,6 +26,16 @@ services:
     restart: on-failure:5
     volumes:
       - elasticsearch:/usr/share/elasticsearch/data:rw
+    environment:
+      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
+    ulimits:
+      memlock:
+        soft: -1
+        hard: -1
+      nofile:
+        soft: 65536
+        hard: 65536
+    mem_limit: 1000000000```

**Comment by ghoul008** [comment]
hi， mem reset，but ES not work
`vm.max_map_count = 262144
[root@mist ~]# docker-compose logs elasticsearch
Attaching to root_elasticsearch_1
elasticsearch_1         | [2020-03-25T02:32:14,549][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1         | [2020-03-25T02:32:14,791][INFO ][o.e.e.NodeEnvironment    ] [5riBZ_8] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/mapper/centos-root)]], net usable_space [38.2gb], net total_space [49.9gb], spins? [possibly], types [xfs]
elasticsearch_1         | [2020-03-25T02:32:14,794][INFO ][o.e.e.NodeEnvironment    ] [5riBZ_8] heap size [1.9gb], compressed ordinary object pointers [true]
elasticsearch_1         | [2020-03-25T02:32:14,833][INFO ][o.e.n.Node               ] node name [5riBZ_8] derived from node ID [5riBZ_8iQ7i_rua5al2pWg]; set [node.name] to override
elasticsearch_1         | [2020-03-25T02:32:14,833][INFO ][o.e.n.Node               ] version[5.6.10], pid[1], build[b727a60/2018-06-06T15:48:34.860Z], OS[Linux/3.10.0-1062.12.1.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_181/25.181-b13]
elasticsearch_1         | [2020-03-25T02:32:14,834][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/usr/share/elasticsearch]
elasticsearch_1         | [2020-03-25T02:32:17,427][INFO ][o.e.p.PluginsService     ] [5riBZ_8] loaded module [aggs-matrix-stats]
elasticsearch_1         | [2020-03-25T02:32:17,427][INFO ][o.e.p.PluginsService     ] [5riBZ_8] loaded module [ingest-common]
elasticsearch_1         | [2020-03-25T02:32:17,428][INFO ][o.e.p.PluginsService     ] [5riBZ_8] loaded module [lang-expression]
elasticsearch_1         | [2020-03-25T02:32:17,428][INFO ][o.e.p.PluginsService     ] [5riBZ_8] loaded module [lang-groovy]
elasticsearch_1         | [2020-03-25T02:32:17,428][INFO ][o.e.p.PluginsService     ] [5riBZ_8] loaded module [lang-mustache]
elasticsearch_1         | [2020-03-25T02:32:17,428][INFO ][o.e.p.PluginsService     ] [5riBZ_8] loaded module [lang-painless]
elasticsearch_1         | [2020-03-25T02:32:17,428][INFO ][o.e.p.PluginsService     ] [5riBZ_8] loaded module [parent-join]
elasticsearch_1         | [2020-03-25T02:32:17,428][INFO ][o.e.p.PluginsService     ] [5riBZ_8] loaded module [percolator]
elasticsearch_1         | [2020-03-25T02:32:17,428][INFO ][o.e.p.PluginsService     ] [5riBZ_8] loaded module [reindex]
elasticsearch_1         | [2020-03-25T02:32:17,428][INFO ][o.e.p.PluginsService     ] [5riBZ_8] loaded module [transport-netty3]
elasticsearch_1         | [2020-03-25T02:32:17,428][INFO ][o.e.p.PluginsService     ] [5riBZ_8] loaded module [transport-netty4]
elasticsearch_1         | [2020-03-25T02:32:17,429][INFO ][o.e.p.PluginsService     ] [5riBZ_8] no plugins loaded
elasticsearch_1         | [2020-03-25T02:32:19,740][INFO ][o.e.d.DiscoveryModule    ] [5riBZ_8] using discovery type [zen]
elasticsearch_1         | [2020-03-25T02:32:20,693][INFO ][o.e.n.Node               ] initialized
elasticsearch_1         | [2020-03-25T02:32:20,693][INFO ][o.e.n.Node               ] [5riBZ_8] starting ...
elasticsearch_1         | [2020-03-25T02:32:20,921][INFO ][o.e.t.TransportService   ] [5riBZ_8] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
elasticsearch_1         | [2020-03-25T02:32:24,014][INFO ][o.e.c.s.ClusterService   ] [5riBZ_8] new_master {5riBZ_8}{5riBZ_8iQ7i_rua5al2pWg}{wfm1izMAQ7aAJ6krAoNFCg}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)[, ]
elasticsearch_1         | [2020-03-25T02:32:24,049][INFO ][o.e.h.n.Netty4HttpServerTransport] [5riBZ_8] publish_address {172.20.0.6:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch_1         | [2020-03-25T02:32:24,049][INFO ][o.e.n.Node               ] [5riBZ_8] started
elasticsearch_1         | [2020-03-25T02:32:24,386][INFO ][o.e.g.GatewayService     ] [5riBZ_8] recovered [2] indices into cluster_state
elasticsearch_1         | [2020-03-25T02:32:24,875][INFO ][o.e.c.r.a.AllocationService] [5riBZ_8] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.kibana][0], [app-logs-2020][0]] ...]).
-------------------------------------------------------------------------------------------------------------
[root@mist ~]# docker logs 097f185a73db
Traceback (most recent call last):
  File "./scripts/add_templates.py", line 68, in add_templates
    es.indices.put_template(name=tname, body=template)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/indices.py", line 564, in put_template
    "PUT", _make_path("_template", name), params=params, body=body
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Field [_id] is defined twice in [request]')
Elasticsearch not up yet
Elasticsearch not up yet
Elasticsearch not up yet
Elasticsearch not up yet
Elasticsearch not up yet
Elasticsearch not up yet
Elasticsearch not up yet
Elasticsearch not up yet
Elasticsearch not up yet
Connected to: elasticsearch
Applying "cloudify-metrics" template... OK
Applying "machines_inventory" template... OK
Applying "exceptions" template... OK
Applying "logs" template... ERROR
Traceback (most recent call last):
  File "./scripts/add_templates.py", line 91, in <module>
    add_templates(args.force)
  File "./scripts/add_templates.py", line 76, in add_templates
    raise Exception("Completed with errors")
Exception: Completed with errors
Connected to: elasticsearch
Applying "cloudify-metrics" template... OK
Applying "machines_inventory" template... OK
Applying "exceptions" template... OK
Applying "logs" template... ERROR
Traceback (most recent call last):
  File "./scripts/add_templates.py", line 68, in add_templates
    es.indices.put_template(name=tname, body=template)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/indices.py", line 564, in put_template
    "PUT", _make_path("_template", name), params=params, body=body
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Field [_id] is defined twice in [request]')
Traceback (most recent call last):
  File "./scripts/add_templates.py", line 91, in <module>
    add_templates(args.force)
  File "./scripts/add_templates.py", line 76, in add_templates
    raise Exception("Completed with errors")
Exception: Completed with errors
Connected to: elasticsearch
Applying "cloudify-metrics" template... OK
Applying "machines_inventory" template... OK
Applying "exceptions" template... OK
Applying "logs" template... ERROR
Traceback (most recent call last):
  File "./scripts/add_templates.py", line 68, in add_templates
    es.indices.put_template(name=tname, body=template)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/indices.py", line 564, in put_template
    "PUT", _make_path("_template", name), params=params, body=body
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Field [_id] is defined twice in [request]')
Traceback (most recent call last):
  File "./scripts/add_templates.py", line 91, in <module>
    add_templates(args.force)
  File "./scripts/add_templates.py", line 76, in add_templates
    raise Exception("Completed with errors")
Exception: Completed with errors
Connected to: elasticsearch
Applying "cloudify-metrics" template... OK
Traceback (most recent call last):
  File "./scripts/add_templates.py", line 68, in add_templates
    es.indices.put_template(name=tname, body=template)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/indices.py", line 564, in put_template
    "PUT", _make_path("_template", name), params=params, body=body
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Field [_id] is defined twice in [request]')
Traceback (most recent call last):
  File "./scripts/add_templates.py", line 91, in <module>
    add_templates(args.force)
  File "./scripts/add_templates.py", line 76, in add_templates
    raise Exception("Completed with errors")
Exception: Completed with errors
Applying "machines_inventory" template... OK
Applying "exceptions" template... OK
Applying "logs" template... ERROR
Connected to: elasticsearch
Applying "cloudify-metrics" template... OK
Applying "machines_inventory" template... OK
Applying "exceptions" template... OK
Applying "logs" template... ERROR
Traceback (most recent call last):
  File "./scripts/add_templates.py", line 68, in add_templates
    es.indices.put_template(name=tname, body=template)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/indices.py", line 564, in put_template
    "PUT", _make_path("_template", name), params=params, body=body
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Field [_id] is defined twice in [request]')
Traceback (most recent call last):
  File "./scripts/add_templates.py", line 91, in <module>
    add_templates(args.force)
  File "./scripts/add_templates.py", line 76, in add_templates
    raise Exception("Completed with errors")
Exception: Completed with errors
Traceback (most recent call last):
  File "./scripts/add_templates.py", line 68, in add_templates
    es.indices.put_template(name=tname, body=template)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/indices.py", line 564, in put_template
    "PUT", _make_path("_template", name), params=params, body=body
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
Connected to: elasticsearch
Applying "cloudify-metrics" template... OK
Applying "machines_inventory" template... OK
Applying "exceptions" template... OK
Applying "logs" template... ERROR
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Field [_id] is defined twice in [request]')
Traceback (most recent call last):
  File "./scripts/add_templates.py", line 91, in <module>
    add_templates(args.force)
  File "./scripts/add_templates.py", line 76, in add_templates
    raise Exception("Completed with errors")
Exception: Completed with errors`

**Comment by ghoul008** [comment]
@d-mo

**Comment by ghoul008** [comment]
[root@mist ~]# docker-compose logs apply-migrations
Attaching to root_apply-migrations_1
apply-migrations_1      | Waiting for elasticsearch:9200
apply-migrations_1      | DOWN: elasticsearch:9200
apply-migrations_1      | DOWN: elasticsearch:9200
apply-migrations_1      | DOWN: elasticsearch:9200
apply-migrations_1      | DOWN: elasticsearch:9200
apply-migrations_1      | DOWN: elasticsearch:9200
apply-migrations_1      | DOWN: elasticsearch:9200
apply-migrations_1      | DOWN: elasticsearch:9200
apply-migrations_1      | UP: elasticsearch:9200
apply-migrations_1      | Waiting for mongodb:27017
apply-migrations_1      | UP: mongodb:27017
apply-migrations_1      | Waiting for rabbitmq:5672
apply-migrations_1      | DOWN: rabbitmq:5672
apply-migrations_1      | DOWN: rabbitmq:5672
apply-migrations_1      | DOWN: rabbitmq:5672
apply-migrations_1      | DOWN: rabbitmq:5672
apply-migrations_1      | UP: rabbitmq:5672
apply-migrations_1      | Waiting for memcached:11211
apply-migrations_1      | UP: memcached:11211
apply-migrations_1      | Will execute command bin/migrate
apply-migrations_1      | MIST_API_DIR is /mist.api
apply-migrations_1      | Couldn't find core config in /src/mist/core/config.py
apply-migrations_1      | Reading settings from /etc/mist/defaults.py
apply-migrations_1      | Reading settings from /etc/mist/settings/settings.py
apply-migrations_1      | 2020-03-25 02:58:12 INFO MainThread __init__ - mongo_connect: Attempting to connect to mist2 at mongodb:27017...
apply-migrations_1      | 2020-03-25 02:58:12 INFO MainThread __init__ - mongo_connect: Connected...
apply-migrations_1      | 2020-03-25 02:58:12 INFO MainThread models - get_unapplied_migrations: No migrations to apply!
apply-migrations_1      | Waiting for elasticsearch:9200
apply-migrations_1      | UP: elasticsearch:9200
apply-migrations_1      | Waiting for mongodb:27017
apply-migrations_1      | UP: mongodb:27017
apply-migrations_1      | Waiting for rabbitmq:5672
apply-migrations_1      | UP: rabbitmq:5672
apply-migrations_1      | Waiting for memcached:11211
apply-migrations_1      | UP: memcached:11211
apply-migrations_1      | Will execute command bin/migrate
apply-migrations_1      | MIST_API_DIR is /mist.api
apply-migrations_1      | Couldn't find core config in /src/mist/core/config.py
apply-migrations_1      | Reading settings from /etc/mist/defaults.py
apply-migrations_1      | Reading settings from /etc/mist/settings/settings.py
apply-migrations_1      | 2020-03-25 03:46:56 INFO MainThread __init__ - mongo_connect: Attempting to connect to mist2 at mongodb:27017...
apply-migrations_1      | 2020-03-25 03:46:56 INFO MainThread __init__ - mongo_connect: Connected...
apply-migrations_1      | 2020-03-25 03:46:56 INFO MainThread models - get_unapplied_migrations: No migrations to apply!

/src/mist/core/config.py not found
