### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by Murtadin** [mistio/mist-ce#985]
Hello dear! Thanks for your work. 
Tried fresh install of mist-ce on centos 8 VM and got an error when trying to access web ui:

502 Bad Gateway.

Any ideas how to fix this issue? Thank you in advance.

nginx logs:

`192.168.111.100 - - [04/Jun/2020:22:16:14 +0000] "GET / HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" "-"

2020/06/04 22:16:15 [error] 9#9: *1 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.111.100, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.19:80/favicon.ico", host: "172.16.128.249", referrer: "http://172.16.128.249/"

192.168.111.100 - - [04/Jun/2020:22:16:15 +0000] "GET /favicon.ico HTTP/1.1" 502 559 "http://172.16.128.249/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" "-"`

P.S.

```
Elasticsearch not up yet
Traceback (most recent call last):
  File "./scripts/add_templates.py", line 91, in <module>
    add_templates(args.force)
  File "./scripts/add_templates.py", line 41, in add_templates
    es = es_client()
  File "./scripts/add_templates.py", line 34, in es_client
    raise Exception()

n
Elasticsearch not up yet
```

**Comment by Murtadin** [comment]
docker-compose logs -f api

`api_1                   | Waiting for elasticsearch:9200
api_1                   | DOWN: elasticsearch:9200
api_1                   | DOWN: elasticsearch:9200
api_1                   | DOWN: elasticsearch:9200
api_1                   | DOWN: elasticsearch:9200
`

pls. help

**Comment by d-mo** [comment]
As you can see in the above log, Elasticsearch is down. This is usually due to not enough RAM. Check the Elasticsearch logs with `docker-compose logs elasticsearch`.

**Comment by Murtadin** [comment]
Hello dear - i do not see any errors in logs:

```
elasticsearch_1         | [2020-06-06T12:42:08,835][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1         | [2020-06-06T12:42:09,032][INFO ][o.e.e.NodeEnvironment    ] [meVfCFa] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/mapper/cl-root)]], net usable_space [29.9gb], net total_space [38.2gb], spins? [possibly], types [xfs]
elasticsearch_1         | [2020-06-06T12:42:09,032][INFO ][o.e.e.NodeEnvironment    ] [meVfCFa] heap size [1.9gb], compressed ordinary object pointers [true]
elasticsearch_1         | [2020-06-06T12:42:09,034][INFO ][o.e.n.Node               ] node name [meVfCFa] derived from node ID [meVfCFaBRmaHyBZKSz0ljg]; set [node.name] to override
elasticsearch_1         | [2020-06-06T12:42:09,034][INFO ][o.e.n.Node               ] version[5.6.10], pid[1], build[b727a60/2018-06-06T15:48:34.860Z], OS[Linux/4.18.0-147.8.1.el8_1.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_181/25.181-b13]
elasticsearch_1         | [2020-06-06T12:42:09,034][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/usr/share/elasticsearch]
elasticsearch_1         | [2020-06-06T12:42:09,801][INFO ][o.e.p.PluginsService     ] [meVfCFa] loaded module [aggs-matrix-stats]
elasticsearch_1         | [2020-06-06T12:42:09,802][INFO ][o.e.p.PluginsService     ] [meVfCFa] loaded module [ingest-common]
elasticsearch_1         | [2020-06-06T12:42:09,802][INFO ][o.e.p.PluginsService     ] [meVfCFa] loaded module [lang-expression]
elasticsearch_1         | [2020-06-06T12:42:09,802][INFO ][o.e.p.PluginsService     ] [meVfCFa] loaded module [lang-groovy]
elasticsearch_1         | [2020-06-06T12:42:09,802][INFO ][o.e.p.PluginsService     ] [meVfCFa] loaded module [lang-mustache]
elasticsearch_1         | [2020-06-06T12:42:09,802][INFO ][o.e.p.PluginsService     ] [meVfCFa] loaded module [lang-painless]
elasticsearch_1         | [2020-06-06T12:42:09,802][INFO ][o.e.p.PluginsService     ] [meVfCFa] loaded module [parent-join]
elasticsearch_1         | [2020-06-06T12:42:09,802][INFO ][o.e.p.PluginsService     ] [meVfCFa] loaded module [percolator]
elasticsearch_1         | [2020-06-06T12:42:09,802][INFO ][o.e.p.PluginsService     ] [meVfCFa] loaded module [reindex]
elasticsearch_1         | [2020-06-06T12:42:09,802][INFO ][o.e.p.PluginsService     ] [meVfCFa] loaded module [transport-netty3]
elasticsearch_1         | [2020-06-06T12:42:09,802][INFO ][o.e.p.PluginsService     ] [meVfCFa] loaded module [transport-netty4]
elasticsearch_1         | [2020-06-06T12:42:09,803][INFO ][o.e.p.PluginsService     ] [meVfCFa] no plugins loaded
elasticsearch_1         | [2020-06-06T12:42:11,958][INFO ][o.e.d.DiscoveryModule    ] [meVfCFa] using discovery type [zen]
elasticsearch_1         | [2020-06-06T12:42:12,847][INFO ][o.e.n.Node               ] initialized
elasticsearch_1         | [2020-06-06T12:42:12,847][INFO ][o.e.n.Node               ] [meVfCFa] starting ...
elasticsearch_1         | [2020-06-06T12:42:13,039][INFO ][o.e.t.TransportService   ] [meVfCFa] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
elasticsearch_1         | [2020-06-06T12:42:16,110][INFO ][o.e.c.s.ClusterService   ] [meVfCFa] new_master {meVfCFa}{meVfCFaBRmaHyBZKSz0ljg}{yA2BENwnRmyySOXoLuYbmQ}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)[, ]
elasticsearch_1         | [2020-06-06T12:42:16,150][INFO ][o.e.h.n.Netty4HttpServerTransport] [meVfCFa] publish_address {172.19.0.27:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch_1         | [2020-06-06T12:42:16,150][INFO ][o.e.n.Node               ] [meVfCFa] started
elasticsearch_1         | [2020-06-06T12:42:16,188][INFO ][o.e.g.GatewayService     ] [meVfCFa] recovered [0] indices into cluster_state

```
btw - vm have 6 cpu and 8gb ram.

**Comment by necouchman** [comment]
FWIW for any who stumble across this issue in the future - while RAM was mentioned in the logs, my issue actually turned out to be the limit of open files for the container. I added a `ulimit` section to the docker-compose.yaml file, for the `elasticsearch` container, and set the limits on the number of open files significantly higher:

```
  elasticsearch:
    image: elasticsearch:5.6.16
    restart: on-failure:5
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:rw
    environment:
      ES_JAVA_OPTS: "-Dlog4j2.formatMsgNoLookups=true"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"

```
